-- CREATE USER myUser;

-- CREATE DATABASE myApp_dev;
-- GRANT ALL PRIVILEGES ON DATABASE myApp_dev TO myUser;

CREATE TABLE IF NOT EXISTS scores (
  id BIGSERIAL NOT NULL PRIMARY KEY,
  name VARCHAR(6) NOT NULL,
  score int NOT NULL,
  timestamp TIMESTAMP NOT NULL,
  v VARCHAR(20) NOT NULL,
  mode VARCHAR(20) NOT NULL
);